### ISSUE TITLE
Question: Upstreaming to unicorn?

### ISSUE THREAD

**Issue by Lewiscowles1986** [Shopify/pitchfork#16]
Hey, your README is a delight by the way. It was easy to understand, it identified provenance; approach. I Really really enjoyed it. Please view my impertinent question remembering that 🙏 .

Do you have plans or a policy to upstream to `unicorn`; and also on what and how you'll take from unicorn. Managing divergent projects can be such a large source of effort, I'm genuinely curious to know if you have a blog dedicated to pitchfork, where I might satisfy my curious nature about the intentions, how that is going, etc.

Have a great weekend, and it's very cool you are trying new things in the open. 👍 🏆

**Comment by casperisfine** [comment]
Thank you for the kind words.

Your question is perfectly legitimate, and @SamSaffron asked the same thing last week on Twitter.

I updated the README in https://github.com/Shopify/pitchfork/commit/122413e9ca357344c9ab020f15c0566828efad87, let me know if that doesn't answer your question well enough.

> I'm genuinely curious to know if you have a blog dedicated to pitchfork

No blog post yet. I may do that when taking Pitchfork out of "experimental" state (may take a tiny while because I won't have lots of time in the coming month or so).

However it was discussed publicly in various places:

  - https://nitter.net/_byroot/status/1577647475686514689
  - https://old.reddit.com/r/ruby/comments/xwcvty/a_new_web_server_github_shopifypitchfork/
  - https://news.ycombinator.com/item?id=33180960

You'll probably find the answer to the questions you might have there.
